package ci.itechciv.sigdep.contracts;

public enum EntityType {
    PATIENTS,
    VISITS,
    DISPENSATIONS,
    SCREENINGS,
    TREATMENT_INITIATIONS,
    PTME_MOTHERS,
    PTME_MOTHER_VISITS,
    PTME_CHILDREN,
    PTME_CHILD_VISITS,
    TPT_RECORDS,
    IVSA_EVALUATIONS,
    LAB_RESULTS,
    CLOSURES
}
